version: '3'

services:
  web:
    image: node:18-alpine
    working_dir: /usr/app
    ports:
      - 9002:9002
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command: sh -c "npm install && npm run start:dev"