version: '3'

services:
  web:
    image: node:18-alpine
    working_dir: /usr/app
    depends_on:
      - postgres
    ports:
      - 9002:9002
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command: sh -c "npm install && npm run start:dev"

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=demo
      - POSTGRES_USER=demo
      - POSTGRES_DB=nnt_demo