name: ci
run-name: continuous integration pipeline
on: [push]

jobs:
  lint-and-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build
      - run: rm -rf dist
      - run: TZ=Europe/Berlin npm run test -- --ci --maxWorkers=2